author: Dale Zak, Sarin Regmi, @maxcheremisin, nashsibanda
name: github-pr-to-trello-card
description: GitHub Action to attach GitHub pull requests to a Trello card
branding:
  icon: "check-square"
  color: "gray-dark"
inputs:
  trello-api-key:
    description: Trello API key, visit https://trello.com/app-key for key
    required: true
  trello-auth-token:
    description: Trello auth token, visit https://trello.com/app-key then click generate a token
    required: true
  trello-card-id-pattern:
    description: Custom JS-compatible regex pattern to extract Trello card shortcode. Defaults to "/tr-[shortcode]/"
    default: "/\/tr-([a-zA-Z0-9]+)\/.*/"
    required: false
runs:
  using: node16
  main: dist/index.js
